### ISSUE TITLE
对象深层属性邦不上去啊！我以为你的可以，发现也不行

### ISSUE THREAD

**Issue by armomu** [bowencool/bue#1]

**Comment by bowencool** [comment]
什么意思

**Comment by armomu** [comment]
b-model="obj.child.name"这样双向绑定就失效了，我在用proxy的时候也遇到这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "博文"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 上午10:23
收件人: "bowencool/bue"<bue@noreply.github.com&gt;; 
抄送: "陈华杰"<894620576@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bowencool/bue] 对象深层属性邦不上去啊！我以为你的可以，发现也不行 (#1)




什么意思

**Comment by bowencool** [comment]
我记得是好的啊，周末有空试一下😂

**Comment by bowencool** [comment]
修复了，看来单元测试还是很重要的🤣

**Comment by armomu** [comment]
niubility




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "博文"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 晚上10:32
收件人: "bowencool/bue"<bue@noreply.github.com&gt;; 
抄送: "陈华杰"<894620576@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bowencool/bue] 对象深层属性邦不上去啊！我以为你的可以，发现也不行 (#1)




修复了，看来单元测试还是很重要的🤣
