### ISSUE TITLE
为什么不用原生的typeof检测类型呢

### ISSUE THREAD

**Issue by yushen7** [bowencool/bue#4]
https://github.com/bowencool/bue/blob/ddcc200afb5ea2123a61c0387ed5218d51eb4a41/src/utils/index.ts#L3

```js 
export function typeOf(wtf: any): string {
	return Object.prototype.toString
		.call(wtf)
		.slice(8, -1)
		.toLowerCase();
}
```

1. 试了一下`typeOf(null)` 返回了`object` ...貌似没有解决`typeof null` 的问题
2. `toString` 的方式会被`Symbol(Symbol.toStringTag)` 改写

针对第2点，如：
```js
a = { 
 get [Symbol.toStringTag]() {
    return "[object,Whatever]";
  }
}
{}
typeOf(a) // [object,whatever]
```
可以使用：`value=> value === null ? 'null' : typeof value`

**Comment by bowencool** [comment]
第一点是好的啊
![image](https://user-images.githubusercontent.com/20217146/88379439-874e3880-cdd5-11ea-8a6e-6754e95dba53.png)
第二点我是真不知道

**Comment by bowencool** [comment]
` value=> value === null ? 'null' : typeof value `
typeof 就是个废物：
![image](https://user-images.githubusercontent.com/20217146/88379832-283cf380-cdd6-11ea-81c4-31ed6942d2df.png)

**Comment by yushen7** [comment]
got it
